### ISSUE TITLE
Can't import PTracker

### ISSUE THREAD

**Issue by mihow** [fullboar/pyvotal#3]
```
$ pip install pyvotal
$ python2.6

>>> from pyvotal import PTracker

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michael/.virtualenvs/aceadmin/lib/python2.6/site-packages/pyvotal/__init__.py", line 18, in <module>
    from pyvotal.ptracker import PTracker
  File "/Users/michael/.virtualenvs/aceadmin/lib/python2.6/site-packages/pyvotal/ptracker.py", line 20, in <module>
    from pyvotal.projects import ProjectManager, Project
  File "/Users/michael/.virtualenvs/aceadmin/lib/python2.6/site-packages/pyvotal/projects.py", line 28, in <module>
    from pyvotal.memberships import MembershipManager
  File "/Users/michael/.virtualenvs/aceadmin/lib/python2.6/site-packages/pyvotal/memberships.py", line 25, in <module>
    from pyvotal.document import PyvotalDocument, PyvotalEmbeddedDocument
  File "/Users/michael/.virtualenvs/aceadmin/lib/python2.6/site-packages/pyvotal/document.py", line 116, in <module>
    PyvotalDocument = diff_id_field(IntField, ['id'])(PyvotalDocument)
  File "/Users/michael/.virtualenvs/aceadmin/lib/python2.6/site-packages/dictshield/document.py", line 606, in wrap
    klass = _swap_field(klass, id_field, field_list)
  File "/Users/michael/.virtualenvs/aceadmin/lib/python2.6/site-packages/dictshield/document.py", line 577, in _swap_field
    if f is klass._meta['id_field']:
AttributeError: type object 'PyvotalDocument' has no attribute '_meta'
```

**Comment by mihow** [comment]
I also installed the latest code from GitHub and I get the same error.

**Comment by zerko** [comment]
Can you check it with dictshield==0.3.6? pip install -U dictshield==0.3.6.

**Comment by mihow** [comment]
That worked thank you! Until the code is updated I set an explicit version of dictshield in the setup.py requirements and made a pull request. https://github.com/fullboar/pyvotal/pull/4

**Comment by zerko** [comment]
Thanks! I will look into possible 0.4 compatibility later this week.

**Comment by zerko** [comment]
Code now should work with both dictshield 0.3.x and 0.4.x
